theme: just-the-docs

title: OpenHPC 
show_downloads: false
markdown: kramdown

logo: "images/ohpc_logo.png"

aux_links:
  "OpenHPC on GitHub":
    - "//github.com/openhpc/ohpc"
aux_links_new_tab: true

footer_content: "Copyright &copy 2020, OpenHPC, a Linux Foundation Collaborative Project. Documentation is available under the <a href=\"http://creativecommons.org/licenses/by/4.0\">Creative Commons Attribution 4.0</a> license."
